export default function Head() {
  return (
    <>
      <title>Julian Bustos Web Developer</title>

      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <script async defer data-website-id="a314cee8-3dd4-43ab-bdf8-3349f35dc42e" src="https://analytics-julimancan.vercel.app/umami.js"></script>

    </>
  )
}
